theme: jekyll-theme-cayman

# Name of website
title: ELR Studio
brief-intro: English lanauge editing

# Short description of your site
description: English Language Editing · Academic Translation · Manuscript Formatting

social-network-links:
  email: "elr.editing@gmail.com"
